name: Generate Doc

on:
  push:
    branches: [ "main" ]

jobs:
  gen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run doc
    - name: update readme
      uses: EndBug/add-and-commit@v9
      with:
        message: Update README.md
        add: README.md
        committer_name: Github Actions
        committer_email: github-actions[bot]@users.noreply.github.com
